import * as THREE from 'three';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { BokehPass } from 'three/examples/jsm/postprocessing/BokehPass.js';
import { ShaderPass } from 'three/examples/jsm/postprocessing/ShaderPass.js';
import { OutputPass } from 'three/examples/jsm/postprocessing/OutputPass.js';
import { t } from '../i18n.js';

const FilterShader={uniforms:{tDiffuse:{value:null},exposure:{value:0},contrast:{value:1},saturation:{value:1},temperature:{value:0},vignette:{value:0},grain:{value:0},time:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform sampler2D tDiffuse;uniform float exposure,contrast,saturation,temperature,vignette,grain,time;varying vec2 vUv;float rnd(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233))+time)*43758.5453);}void main(){vec4 s=texture2D(tDiffuse,vUv);vec3 c=s.rgb*exp2(exposure);float l=dot(c,vec3(.2126,.7152,.0722));c=mix(vec3(l),c,saturation);c=(c-.5)*contrast+.5;c+=temperature*vec3(.09,.025,-.08);float e=smoothstep(.82,.2,length((vUv-.5)*vec2(1.,.75)));c*=mix(1.-vignette,1.,e);c+=(rnd(vUv*2048.)-.5)*grain;gl_FragColor=vec4(max(c,0.),s.a);}`};
const num=(e,f)=>{const n=Number(e?.value);return Number.isFinite(n)?n:f;};
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}

export class PhotoMode{
 constructor(options){Object.assign(this,options);this.active=false;this.paused=true;this.locked=true;this.keys=new Set();this.moveSpeed=12;this.roll=0;this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();const ids=['close','lock','reset','camera-status','camera-help','hide-hud','fov','roll','speed','sim-rate','pause','step','network-status','sim-status','scene-time','time-now','dof','focus','focus-rover','aperture','blur','preset','exposure','contrast','saturation','temperature','vignette','grain','sticker','caption','resolution','save','status'];this.ui=Object.fromEntries(ids.map(x=>[x.replaceAll('-','_'),document.querySelector('#photo-'+x)]));this.bindUi();this.bindControls();this.refreshLanguage();}
 bindUi(){const u=this.ui;u.close.onclick=()=>this.exit();u.lock.onclick=()=>this.setLocked(!this.locked);u.reset.onclick=()=>this.resetCamera();u.hide_hud.onchange=()=>this.applyHud();u.fov.oninput=()=>{this.camera.fov=num(u.fov,56);this.camera.updateProjectionMatrix();};u.roll.oninput=()=>this.roll=THREE.MathUtils.degToRad(num(u.roll,0));u.speed.oninput=()=>this.moveSpeed=num(u.speed,12);u.sim_rate.onchange=()=>{this.stepPending=false;this.paused=num(u.sim_rate,0)===0;u.sim_rate.blur();this.syncTimeButtons();};u.pause.onclick=()=>{if(this.networked())return;this.stepPending=false;this.paused=!this.paused;if(!this.paused&&num(u.sim_rate,0)===0)u.sim_rate.value='1';this.syncTimeButtons();};u.step.onclick=()=>this.queueStep();u.scene_time.onchange=()=>{if(u.scene_time.value)this.setDate(new Date(u.scene_time.value+'Z'));};u.time_now.onclick=()=>{this.setDate(new Date());this.syncSceneTime(true);};['dof','focus','aperture','blur','exposure','contrast','saturation','temperature','vignette','grain'].forEach(k=>{u[k].oninput=()=>this.applyEffects();u[k].onchange=()=>this.applyEffects();});u.focus_rover.onclick=()=>this.focusRover();u.preset.onchange=()=>this.applyPreset(u.preset.value);u.save.onclick=()=>this.capture();}
 bindControls(){const c=this.renderer.domElement;c.addEventListener('pointerdown',e=>{if(!this.active||e.button!==0)return;this.dragging=true;this.lastX=e.clientX;this.lastY=e.clientY;c.setPointerCapture(e.pointerId);});c.addEventListener('pointermove',e=>{if(!this.active||!this.dragging)return;const dx=e.clientX-this.lastX,dy=e.clientY-this.lastY;this.lastX=e.clientX;this.lastY=e.clientY;if(this.locked){this.orbitYaw-=dx*.005;this.orbitPitch=THREE.MathUtils.clamp(this.orbitPitch+dy*.004,-1.35,1.35);}else{this.freeYaw-=dx*.004;this.freePitch=THREE.MathUtils.clamp(this.freePitch-dy*.0035,-1.5,1.5);}});const end=()=>this.dragging=false;c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);c.addEventListener('wheel',e=>{if(!this.active)return;e.preventDefault();if(this.locked)this.orbitRadius=THREE.MathUtils.clamp(this.orbitRadius*Math.exp(e.deltaY*.001),2.5,250);else this.moveSpeed=THREE.MathUtils.clamp(this.moveSpeed*Math.exp(-e.deltaY*.001),.5,250);this.ui.speed.value=String(this.moveSpeed);},{passive:false});c.addEventListener('dblclick',e=>{if(!this.active)return;const r=c.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObjects(this.scene.children,true).find(x=>x.distance>this.camera.near);if(hit){this.ui.focus.value=String(THREE.MathUtils.clamp(hit.distance,.5,5000));this.applyEffects();}});addEventListener('keydown',e=>{if(!this.active)return;const editingText=e.target.matches?.('textarea,input[type="text"],input[type="number"],input[type="datetime-local"]');if(e.code==='ArrowRight'&&!e.repeat&&!this.networked()&&!editingText){e.preventDefault();e.target.blur?.();this.queueStep();return;}if(e.code==='Escape'&&!e.repeat){e.preventDefault();this.exit();return;}if(e.target.closest?.('input,textarea,select'))return;const move=['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight'];if(move.includes(e.code)){e.preventDefault();this.keys.add(e.code);}if(e.code==='KeyH'&&!e.repeat){e.preventDefault();this.ui.hide_hud.checked=!this.ui.hide_hud.checked;this.applyHud();}if(e.code==='Space'&&!e.repeat&&!this.networked()){e.preventDefault();this.ui.pause.click();}});addEventListener('keyup',e=>this.keys.delete(e.code));addEventListener('blur',()=>{this.keys.clear();this.dragging=false;});}
 queueStep(){if(this.networked())return;this.paused=true;this.ui.sim_rate.value='0';this.stepPending=true;this.syncTimeButtons();if(this.ui.sim_status){this.ui.sim_status.textContent=t('photo.frameAdvanced');clearTimeout(this.stepStatusTimer);this.stepStatusTimer=setTimeout(()=>this.syncTimeButtons(),700);}}
 networked(){return Boolean(this.isNetworked?.());}
 ensureComposer(){if(this.composer)return;this.composer=new EffectComposer(this.renderer);this.renderPass=new RenderPass(this.scene,this.camera);this.bokehPass=new BokehPass(this.scene,this.camera,{focus:12,aperture:.00002,maxblur:.008});this.filterPass=new ShaderPass(FilterShader);this.outputPass=new OutputPass();[this.renderPass,this.bokehPass,this.filterPass,this.outputPass].forEach(p=>this.composer.addPass(p));this.resize(innerWidth,innerHeight);this.applyEffects();}
 disposeComposer(){if(!this.composer)return;this.bokehPass.dispose();this.filterPass.dispose?.();this.outputPass.dispose?.();this.composer.dispose();this.composer=this.renderPass=this.bokehPass=this.filterPass=this.outputPass=null;}
 enter(){if(this.active||!this.rover.ready||!this.rover.object.visible)return false;this.snapshot={position:this.camera.position.clone(),quaternion:this.camera.quaternion.clone(),up:this.camera.up.clone(),fov:this.camera.fov};this.active=true;this.locked=true;this.paused=!this.networked();this.stepPending=false;this.panel.hidden=false;this.ui.hide_hud.checked=true;this.ui.sim_rate.value=this.networked()?'1':'0';this.camera.rotation.order='YXZ';this.syncSceneTime(true);this.syncOrbit();this.ensureComposer();this.applyHud();this.syncNetwork(true);this.syncLock();this.onActiveChange(true);return true;}
 exit(){if(!this.active)return;this.active=false;this.keys.clear();this.dragging=false;this.panel.hidden=true;document.body.classList.remove('photo-clean-view');if(this.snapshot){this.camera.position.copy(this.snapshot.position);this.camera.quaternion.copy(this.snapshot.quaternion);this.camera.up.copy(this.snapshot.up);this.camera.fov=this.snapshot.fov;this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();}this.disposeComposer();this.onActiveChange(false);}
 toggle(){return this.active?(this.exit(),false):this.enter();}
 setLocked(v){if(this.locked===v)return;this.locked=v;v?this.syncOrbit():this.syncFree();this.syncLock();}
 syncLock(){this.ui.lock.textContent=t(this.locked?'photo.switchFree':'photo.switchLock');if(this.ui.camera_status)this.ui.camera_status.textContent=t(this.locked?'photo.cameraModeLocked':'photo.cameraModeFree');if(this.ui.camera_help)this.ui.camera_help.textContent=t(this.locked?'photo.cameraHelpLocked':'photo.cameraHelpFree');}
 syncOrbit(){const o=this.camera.position.clone().sub(this.rover.object.position);this.orbitRadius=THREE.MathUtils.clamp(o.length(),2.5,250);this.orbitYaw=Math.atan2(o.x,o.z);this.orbitPitch=Math.asin(THREE.MathUtils.clamp(o.y/this.orbitRadius,-1,1));}
 syncFree(){const e=new THREE.Euler().setFromQuaternion(this.camera.quaternion,'YXZ');this.freePitch=e.x;this.freeYaw=e.y;}
 resetCamera(){const p=this.rover.object.position,f=new THREE.Vector3(0,0,-1).applyQuaternion(this.rover.object.quaternion).setY(0).normalize();if(f.lengthSq()<.1)f.set(0,0,-1);this.orbitRadius=12;this.orbitPitch=.22;this.orbitYaw=Math.atan2(-f.x,-f.z);this.locked=true;this.roll=0;this.ui.roll.value='0';this.ui.fov.value='50';this.camera.fov=50;this.camera.position.copy(p).addScaledVector(f,-11).add(new THREE.Vector3(0,3.2,0));this.camera.lookAt(p);this.camera.updateProjectionMatrix();this.syncLock();}
 focusRover(){this.ui.focus.value=String(THREE.MathUtils.clamp(this.camera.position.distanceTo(this.rover.object.position),.5,5000).toFixed(2));this.applyEffects();}
 applyHud(){document.body.classList.toggle('photo-clean-view',this.active&&this.ui.hide_hud.checked);}
 syncNetwork(force=false){const online=this.networked();if(!force&&online===this.lastNetworked)return;this.lastNetworked=online;this.ui.network_status.textContent=t(online?'photo.networkLive':'photo.offlinePause');[this.ui.sim_rate,this.ui.pause,this.ui.step].forEach(e=>e.disabled=online);if(online){this.paused=false;this.ui.sim_rate.value='1';}this.syncTimeButtons();}
 syncTimeButtons(){this.ui.pause.textContent=t(this.paused?'photo.resume':'photo.pause');if(this.ui.sim_status)this.ui.sim_status.textContent=this.paused?t('photo.timePaused'):t('photo.timeRunning',{rate:num(this.ui.sim_rate,1)});}
 syncSceneTime(force=false){if(force||document.activeElement!==this.ui.scene_time){const d=this.getDate();if(d instanceof Date&&Number.isFinite(d.getTime()))this.ui.scene_time.value=d.toISOString().slice(0,19);}}
 refreshLanguage(){this.syncLock();this.syncTimeButtons();if(this.active)this.syncNetwork(true);}
 simulationDelta(dt){if(!this.active||this.networked())return dt;if(this.stepPending){this.stepPending=false;return 1/30;}if(this.paused)return 0;return dt*Math.max(0,num(this.ui.sim_rate,1));}
 update(dt){if(!this.active)return;this.syncNetwork();this.syncSceneTime();if(this.locked){const p=this.rover.object.position,c=Math.cos(this.orbitPitch);this.camera.position.set(p.x+Math.sin(this.orbitYaw)*c*this.orbitRadius,p.y+Math.sin(this.orbitPitch)*this.orbitRadius,p.z+Math.cos(this.orbitYaw)*c*this.orbitRadius);this.camera.up.set(0,1,0);this.camera.lookAt(p);this.camera.rotateZ(this.roll);}else{const boost=this.keys.has('ShiftLeft')||this.keys.has('ShiftRight')?4:1,f=new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(this.freePitch,this.freeYaw,0,'YXZ')),r=new THREE.Vector3().crossVectors(f,new THREE.Vector3(0,1,0)).normalize(),m=new THREE.Vector3();if(this.keys.has('KeyW'))m.add(f);if(this.keys.has('KeyS'))m.sub(f);if(this.keys.has('KeyD'))m.add(r);if(this.keys.has('KeyA'))m.sub(r);if(this.keys.has('KeyE'))m.y++;if(this.keys.has('KeyQ'))m.y--;if(m.lengthSq())this.camera.position.addScaledVector(m.normalize(),this.moveSpeed*boost*dt);this.camera.rotation.set(this.freePitch,this.freeYaw,this.roll,'YXZ');}this.camera.updateMatrixWorld(true);if(this.filterPass)this.filterPass.uniforms.time.value=performance.now()*.001;}
 applyEffects(){if(!this.composer)return;const u=this.ui;this.bokehPass.enabled=u.dof.checked;this.bokehPass.uniforms.focus.value=num(u.focus,12);const a=num(u.aperture,25)/100;this.bokehPass.uniforms.aperture.value=.000002+a*a*.00008;this.bokehPass.uniforms.maxblur.value=num(u.blur,35)*.00035;const f=this.filterPass.uniforms;f.exposure.value=num(u.exposure,0);f.contrast.value=num(u.contrast,100)/100;f.saturation.value=num(u.saturation,100)/100;f.temperature.value=num(u.temperature,0)/100;f.vignette.value=num(u.vignette,0)/100;f.grain.value=num(u.grain,0)/1000;}
 applyPreset(name){const v={raw:[0,100,100,0,0,0],cinema:[-.08,118,84,-8,32,8],warm:[.08,106,108,22,14,3],mono:[.02,115,0,0,25,10]}[name]||[0,100,100,0,0,0],c=[this.ui.exposure,this.ui.contrast,this.ui.saturation,this.ui.temperature,this.ui.vignette,this.ui.grain];c.forEach((x,i)=>x.value=String(v[i]));this.applyEffects();}
 render(dt=0){if(!this.active)return false;this.ensureComposer();this.composer.render(dt);return true;}
 resize(w,h){this.composer?.setSize(w,h);}
 outputSize(){const m=this.ui.resolution.value,a=innerWidth/Math.max(1,innerHeight);let w,h;if(m==='4k'){w=3840;h=Math.round(w/a);}else{const s=m==='2'?2:1;w=Math.round(innerWidth*s);h=Math.round(innerHeight*s);}const max=this.renderer.capabilities.maxTextureSize||4096,fit=Math.min(1,max/w,max/h);return{width:Math.max(1,Math.floor(w*fit)),height:Math.max(1,Math.floor(h*fit))};}
 drawSticker(ctx,w,h){const s=this.ui.sticker.value,caption=this.ui.caption.value.trim();if(s==='none'&&!caption)return;const pad=Math.round(Math.min(w,h)*.035),big=Math.max(18,Math.round(Math.min(w,h)*.026)),small=Math.max(12,Math.round(big*.55));ctx.save();ctx.textBaseline='bottom';ctx.shadowColor='rgba(0,0,0,.9)';ctx.shadowBlur=Math.max(4,Math.round(big*.25));if(s==='mission'){ctx.fillStyle='#f4f7f4';ctx.font=`800 ${big}px system-ui,sans-serif`;ctx.fillText('LUNAR SIM',pad,h-pad-small*1.4);ctx.fillStyle='#9fffd6';ctx.font=`600 ${small}px ui-monospace,monospace`;ctx.fillText(this.getDate().toISOString().replace('T',' ').slice(0,19)+' UTC',pad,h-pad);}else if(s==='coords'){const g=this.getGeo();if(g){ctx.fillStyle='#effffb';ctx.font=`700 ${small}px ui-monospace,monospace`;ctx.fillText(`${g.lat.toFixed(5)}°, ${g.lon.toFixed(5)}°`,pad,h-pad);}}if(caption){ctx.fillStyle='#fff';ctx.font=`700 ${big}px system-ui,sans-serif`;ctx.fillText(caption,w-pad-ctx.measureText(caption).width,h-pad);}ctx.restore();}
 async capture(){if(!this.active||this.capturing)return;this.capturing=true;this.ui.save.disabled=true;this.ui.status.textContent=t('photo.saving');const pr=this.renderer.getPixelRatio(),aspect=this.camera.aspect,{width:w,height:h}=this.outputSize();try{this.renderer.setPixelRatio(1);this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.composer.setPixelRatio(1);this.composer.setSize(w,h);this.composer.render(0);const out=document.createElement('canvas');out.width=w;out.height=h;const ctx=out.getContext('2d');ctx.drawImage(this.renderer.domElement,0,0,w,h);this.drawSticker(ctx,w,h);const blob=await new Promise((ok,no)=>out.toBlob(b=>b?ok(b):no(new Error('PNG encoding failed')),'image/png'));const g=this.getGeo(),coord=g?`${g.lat.toFixed(4)}_${g.lon.toFixed(4)}`:'moon',stamp=this.getDate().toISOString().replace(/[:.]/g,'-');saveBlob(blob,`lunar_photo_${coord}_${stamp}.png`);this.ui.status.textContent=t('photo.saved');}catch(e){console.error('[PhotoMode]',e);this.ui.status.textContent=t('photo.failed');}finally{this.renderer.setPixelRatio(pr);this.renderer.setSize(innerWidth,innerHeight,false);this.camera.aspect=aspect;this.camera.updateProjectionMatrix();this.composer.setPixelRatio(pr);this.composer.setSize(innerWidth,innerHeight);this.ui.save.disabled=false;this.capturing=false;setTimeout(()=>this.ui.status.textContent='',1800);}}
}
